### PR TITLE
Make the current index of the round-robin balancer thread-safe

### PR DESCRIPTION
**Pull request by biningo**
fixes: #19

### CODE REVIEW

**Comment by zehuamama** [comment]
流水线挂了，看看是不是因为 go 版本的问题

**Comment by biningo** [comment]
> 流水线挂了，看看是不是因为 go 版本的问题

Can I upgrade to go 1.21 ?

**Comment by zehuamama** [comment]
golint 发现有个包好像废弃了，看看能不能帮我修复一下，辛苦～

**Comment by biningo** [comment]
Sorry, I will make another pr later to fix the golangci-lint check. Thanks~ ^_^

**Comment by zehuamama** [comment]
> Sorry, I will make another pr later to fix the golangci-lint check. Thanks~ ^_^

没事，我已经把它修好了哈

**Pull request merged**
